version: '3.8'

services:
  app:
    build: 
      context: ./flask-server
      dockerfile: Dockerfile
    container_name: flask_server
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./flask-server/app:/app
    networks:
      - flask_network

networks:
  flask_network:
