name: Flask Server CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout del código
        uses: actions/checkout@v3
 
      - name: "Go to flask-server folder"
        run: cd flask-server

      - name: Configurar Docker
        run: |
          docker build -t flask-server .
          docker run -d -p 5000:5000 --name flask-test-ci flask-server
          sleep 5

      - name: Testear los endpoints
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/ping)
          if [ "$RESPONSE" -ne 200 ]; then exit 1; fi
          
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/status)
          if [ "$RESPONSE" -ne 200 ]; then exit 1; fi

      - name: Finalizar contenedor
        run: docker stop flask-test-ci && docker rm flask-test-ci