name: Scheduled Job

on:
  schedule:
    - cron: '*/10 * * * *'  # runs every 10 seconds

jobs:
  scheduled-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Scheduled Task
        run: echo "This job runs every 10 seconds!"
